{% set name = "CompStats" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/compstats-{{ version }}.tar.gz
  sha256: 40ccb6729048d6f821631cafa1f9b975c71bda96f629e053252c965298d80b2c

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - setuptools
    - pip
    - python >=3.7
  run:
    - scikit-learn >=1.3.0
    - pandas
    - seaborn
    - python >=3.7

test:
  imports:
    - CompStats
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/CompStats
  summary: Competition Statistics Library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
