{% set name = "CompStats" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/compstats-{{ version }}.tar.gz
  sha256: 65885cdb4d852a3d930327828b6633b72c517df4cbbbbf1d8fc8daaec146993c

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - setuptools
    - pip
    - python {{ python_min }}
  run:
    - scikit-learn >=1.3.0
    - pandas
    - seaborn
    - python >={{ python_min }}

test:
  imports:
    - CompStats
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/CompStats
  summary: Competition Statistics Library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
